In [1]:
import pandas as pd
import numpy as np

In [2]:

from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
import pandas as pd

df = pd.read_csv('/content/data.csv')

In [12]:
df.head()

    Назва  Кількість  Ціна
0    Кава         10    80
1     Чай         15    50
2   Цукор         20    35
3  Молоко         12    40

In [14]:
print("Розмірність:", df.shape)

Розмірність: (4, 3)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Назва      4 non-null      object
 1   Кількість  4 non-null      int64
 2   Ціна       4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [16]:
df.describe()

       Кількість       Ціна
count   4.000000   4.000000
mean   14.250000  51.250000
std     4.349329  20.155644
min    10.000000  35.000000
25%    11.500000  38.750000
50%    13.500000  45.000000
75%    16.250000  57.500000
max    20.000000  80.000000

In [18]:
arr = np.array([10, 20, 30, 40, 50])

In [19]:
print("Масив:", arr)

Масив: [10 20 30 40 50]

In [20]:
print("Тип елементів:", arr.dtype)

Тип елементів: int64

In [21]:
print("Форма масиву:", arr.shape)

Форма масиву: (5,)

In [22]:
arr2 = arr * 2

In [23]:
print("Помножений масив:", arr2)

Помножений масив: [ 20  40  60  80 100]

In [24]:
arr3 = arr + 5

In [25]:
print("Масив після додавання 5:", arr3)

Масив після додавання 5: [15 25 35 45 55]

In [26]:
print("Сума:", arr.sum())

Сума: 150

In [27]:
print("Середнє:", arr.mean())

Середнє: 30.0

In [28]:
print("Мінімум:", arr.min())

Мінімум: 10

In [29]:
print("Максимум:", arr.max())

Максимум: 50