## Завдання 1. Імпорт бібліотек і версії

In [1]:
import pandas as pd
import numpy as np

print("Версія pandas:", pd.__version__)
print("Версія numpy:", np.__version__)

Версія pandas: 2.2.3
Версія numpy: 2.1.3

## Завдання 2. Створення CSV та зчитування у DataFrame
Створюємо тестовий файл (12 рядків, 5 колонок), зчитуємо його та виводимо перші й останні 3 рядки.

In [2]:
test = pd.DataFrame({
    'date': pd.date_range('2026-10-01', periods=12).strftime('%Y-%m-%d'),
    'hour': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    'payment': ['card', 'cash', 'card', 'card', 'cash', 'card',
                'cash', 'card', 'card', 'cash', 'card', 'card'],
    'drink': ['Latte', 'Espresso', 'Cappuccino', 'Latte', 'Americano', 'Mocha',
              'Latte', 'Espresso', 'Cappuccino', 'Americano', 'Latte', 'Mocha'],
    'money': [38.7, 28.9, 35.0, 38.7, 30.0, 40.5, 38.7, 28.9, 35.0, 30.0, 38.7, 40.5]
})
test.to_csv('test_sales.csv', index=False)

df = pd.read_csv('test_sales.csv')
print("Перші 3 рядки:")
display(df.head(3))
print("Останні 3 рядки:")
display(df.tail(3))

Перші 3 рядки:

         date  hour payment       drink  money
0  2026-10-01     8    card       Latte   38.7
1  2026-10-02     9    cash    Espresso   28.9
2  2026-10-03    10    card  Cappuccino   35.0

Останні 3 рядки:

          date  hour payment      drink  money
9   2026-10-10    17    cash  Americano   30.0
10  2026-10-11    18    card      Latte   38.7
11  2026-10-12    19    card      Mocha   40.5

## Завдання 3. Назви колонок

In [3]:
cols = df.columns
print(cols)
print("Тип змінної:", type(cols))

Index(['date', 'hour', 'payment', 'drink', 'money'], dtype='object')
Тип змінної: <class 'pandas.core.indexes.base.Index'>

## Завдання 4. Одновимірний масив NumPy (перші 10 парних чисел)

In [4]:
even = np.arange(2, 21, 2)   # 2, 4, ..., 20
print("Масив:", even)
print("Сума:", even.sum())
print("Середнє:", even.mean())
print("Мінімум:", even.min())
print("Максимум:", even.max())
print("Масив × 3:", even * 3)

Масив: [ 2  4  6  8 10 12 14 16 18 20]
Сума: 110
Середнє: 11.0
Мінімум: 2
Максимум: 20
Масив × 3: [ 6 12 18 24 30 36 42 48 54 60]

## Завдання 5. Двовимірний масив 3×3

In [5]:
rng = np.random.default_rng()
m = rng.integers(1, 11, size=(3, 3))   # верхня межа не включається => 1..10
print("Матриця:\n", m)
print("Сума за стовпцями (axis=0):", m.sum(axis=0))
print("Сума за рядками (axis=1):", m.sum(axis=1))

Матриця:
 [[2 2 1]
 [7 6 3]
 [5 3 9]]
Сума за стовпцями (axis=0): [14 11 13]
Сума за рядками (axis=1): [ 5 16 17]

## Завдання 6. Markdown-форматування

### Приклад заголовка третього рівня
Переваги текстових комірок:
- пояснення поруч із кодом і результатами в одному документі;
- **структура** ноутбука (розділи, заголовки, зміст);
- ноутбук можна показати викладачеві або колегам як готовий звіт.

**Пояснення.** Текстові комірки перетворюють набір команд на зрозумілий документ: у них фіксують мету кроку, припущення та висновки. Це полегшує повторне використання, перевірку й захист роботи.

## Завдання 7. Монтування Google Диска та зчитування CSV з Диска

In [6]:
from google.colab import drive
import os, shutil

drive.mount('/content/drive')

path = '/content/drive/MyDrive/test_sales.csv'
# якщо файлу на Диску ще немає, копіюємо тестовий файл із завдання 2
if not os.path.exists(path):
    shutil.copy('test_sales.csv', path)

df_drive = pd.read_csv(path)
df_drive.info()

Mounted at /content/drive
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     12 non-null     object
 1   hour     12 non-null     int64
 2   payment  12 non-null     object
 3   drink    12 non-null     object
 4   money    12 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 612.0+ bytes

In [7]:
print("Порівняння dtypes:")
print(pd.DataFrame({'Завдання 2': df.dtypes, 'Диск': df_drive.dtypes}))

Порівняння dtypes:
        Завдання 2     Диск
date        object   object
hour         int64    int64
payment     object   object
drink       object   object
money      float64  float64

**Висновок про типи даних.** У наборі переважають текстові типи (`object` або `str` залежно від версії pandas: колонки `date`, `payment`, `drink`) та числові `int64` (`hour`) і `float64` (`money`). Типи збігаються з завданням 2, бо дані ті самі. Колонка `date` зчитується як текст, а не `datetime64`; для перетворення потрібен `pd.to_datetime`.

## ★ Додаткове завдання. Комплексний аналіз

**Крок 1.** Зчитуємо CSV-файл у DataFrame.

In [8]:
df_full = pd.read_csv('test_sales.csv')

**Крок 2.** Первинний огляд: перші рядки та розмірність.

In [9]:
display(df_full.head())
print("Розмірність:", df_full.shape)

         date  hour payment       drink  money
0  2026-10-01     8    card       Latte   38.7
1  2026-10-02     9    cash    Espresso   28.9
2  2026-10-03    10    card  Cappuccino   35.0
3  2026-10-04    11    card       Latte   38.7
4  2026-10-05    12    cash   Americano   30.0

Розмірність: (12, 5)

**Крок 3.** Типи колонок і кількість непорожніх значень.

In [10]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     12 non-null     object
 1   hour     12 non-null     int64
 2   payment  12 non-null     object
 3   drink    12 non-null     object
 4   money    12 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 612.0+ bytes

**Крок 4.** Статистичний опис числових колонок (середнє, стандартне відхилення, квартилі).

In [11]:
df_full.describe()

            hour     money
count  12.000000  12.00000
mean   13.500000  35.30000
std     3.605551   4.65735
min     8.000000  28.90000
25%    10.750000  30.00000
50%    13.500000  36.85000
75%    16.250000  38.70000
max    19.000000  40.50000

**Крок 5.** Перетворюємо числову колонку `money` на масив NumPy та обчислюємо середнє.

In [12]:
money = df_full['money'].to_numpy()
print("Масив:", money)
print("Середнє (NumPy):", money.mean())
print("Середнє (pandas):", df_full['money'].mean())

Масив: [38.7 28.9 35.  38.7 30.  40.5 38.7 28.9 35.  30.  38.7 40.5]
Середнє (NumPy): 35.3
Середнє (pandas): 35.3